### ISSUE TITLE
getting express and docker to serve static images

### ISSUE THREAD

**Issue by headwinds** [stephengardner/docker-node-typescript#1]
I've downloaded and installed your demo - works like a charm!

I did what I thought would be a real simple test by adding an image to the index page 

```
<div>
      <img src='images/goldberg.svg'></img>
      <h1>Project Test</h1>
      <h4>details here...</h4>
    </div>
```

I've reviewed the documentation for [Express to serve static file](https://expressjs.com/en/starter/static-files.html) and still nothing... I get a broken link. Any advice?

**Comment by headwinds** [comment]
It was my fault - I missed how you setup the app and required express in one line at the top - once I added express separately - it worked as described in the docs and I can display images now

```
const express = require('express');
const app = require('express')();
const http = require('http');
const server = http.createServer(app);
const io = require('socket.io')(server);

app.use(express.static(__dirname + '/public'));
```

**Comment by headwinds** [comment]
I'll go ahead and close this issue - might also be nice to add it to the project too - I could also do a pull request and simply display the logos from the readme in a header...

**Comment by stephengardner** [comment]
Awesome, I was going to check this out when I had a moment. I can certainly add some documentation and/or examples. I'll give this a look later today thank you

**Comment by headwinds** [comment]
@stephengardner that's cool - it's a powerful starter project and having sample static files is one less hoop to jump through ;-D
